apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-catalog
  template:
    metadata:
      labels:
        app: event-catalog
    spec:
      containers:
        - name: event-catalog
          image: me-central1-docker.pkg.dev/globomantics-globoticket/globoticket/events
          ports:
            - containerPort: 3000
              name: events-port
---
apiVersion: v1
kind: Service
metadata:
  name: event-catalog-service
spec:
  selector:
    app: event-catalog
  ports:
    - protocol: TCP
      port: 3000
      targetPort: events-port
  type: LoadBalancer
